import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router';
import { useEffect } from 'react';


export default function Home() {

  const { push } = useRouter();

  useEffect(() => {
    const item = localStorage.getItem('login')
    if(item) {
      push('/tool-kit');
    } else {
      push('/sign-up');
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.ldsRipple}><div></div><div></div></div>
      </main>
    </>
  )
}
